name: Login to Azure

on:
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    login_to_azure:
        runs-on: ubuntu-latest
        steps:
            - name: Create Login to Azure
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


            